language: php
php:
- 7.2
addons:
  apt:
    packages:
    - jq
    - docker-ce
sudo: required
services:
- docker
before_install:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker pull arm32v7/php:7-cli
- docker pull php:7-cli
- docker pull resin/rpi-raspbian:stretch
- composer install
script:
- docker build . -t 421p/mophpidy:latest -f build/amd/Dockerfile
- docker build . -t 421p/mophpidy:${APP_VERSION} -f build/amd/Dockerfile
- docker build . -t 421p/mophpidy:arm32v7 -f build/arm/Dockerfile
- docker build . -t 421p/mophpidy:${APP_VERSION}-arm32v7 -f build/arm/Dockerfile
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
deploy:
  provider: script
  script: bash docker-deploy
  on:
    branch: master
env:
  global:
  - APP_VERSION=$(cat composer.json | jq -r '.version')
  - secure: nsHoBsaC9PVaoY8MrWnCGE17epXcZI8rIuoVsOjTOlAQo0sjh/PYZHAAEarskxD42kncMGn8DS6iTrxqNbU/FBO36cLNd5bHQdJSJieFdB/AXkUwMSeGhCKXAbhO8t7cTQnoaLMX3sGYBe1Bccb8iKYjseSlPfzzYoD0j2sPIqzeZSZnV2z2uIe5RYWJVhcQ7loBmTEpMd+xd4NwOJ5HZ7iBl29SRoXCU2mLb06z1qmvwwfMntCv0A+XrBFVCCA7wbYqofcCUyz02X5K3gy87HcSq0j3uKAo/5ntbNbZq/rtAspTTWQn5q8aYnutlnCsYH2roNJrniWQBksVqYv3zP0tt8A0Abh4T9ydzEXAszvYjitodvnHG7sP8DkDmMXSnDxiypd+EZ6MyPkyhMvBviQZtjxuRb5nayBq/YVUuSvHCmx5FpXaZnhvYqwxec+FCIiKKezp0GdFP3oiCrcxqo2nIyPDMJAMMdhHsRKnleyT+LG8SwOa3tTEIVux2JSq3BEKp1FNvzPnpM0lcw3FksygXe+nroEszR+F1L5DNuCwKGhb3mLyXxCHUSZhktz5w9boeYIFp07MrotqZYAmW0GiH2KsjDm8r85jGgxFPc+ZCUPdoVVEPt41ahuBXcbqO0V6J0ROXZvbjzNNvLYjELEVyefXOAbu39V+Z6IVWOs=
  - secure: PJUEwkhHUBHhXJICLYhSkYzEojIYBH+mzr8rV9JXGY+SLmtfLLwHeOXbHCstUuKX8mESX0kwfYc0vF82vC0sZIBXgG+hvQRXL1bkQEpjQjWCvfrmaYN1SxCeMEUS09p2ZvYMif2+Gdeo76KSZCkpcEcYOKtLYrIvM6zLU8aFJAV1hECz1K0UCZ5NQfQBTh/iZRlpQTwTJtd1bYlnNbT2WU4uJ8lxfq/ukwD8qkvD5RW5rtWDpohAoOIhQ8fxnY7J4BZjIyPifQNMhu3YYQzAZ4WwRu0xAthlftoqHg0OyjK8kfAxvT4sh5uxIsaKmECxIh3d7qlL4vmwN7sjzs9RJH8xWc3dvK+tyNWgrUvJX3Fmgx73gLFn3kwwVr9jb3Jth+7qB+WSXd1eZvHuiYr/aXtabBVPbe2NMblIq5cKObHNXkyqV/gu8bUFbxnHZp7/z/apk/bEJbJK2BOaDNDtSVczK7csM7dh+ajkwL2Wsf9FOLpj6gAoJAKrnAyhEYWa+Gd8q6DfnmIcPO0EG39qZKEl8z+qzZLnR5CRBJo56ceMlwRuyr5Dub0z4gmo1tj6UYaqtmZbCRNhw/KehKIZoU96Ig2FE4CbHBSOCrsXfN3dSCGz45cHoLCztXOWj4lkfv9r7aBs+PQoA8aZnDYNM4KvZuGJLr7kaBFyflI/q5k=
