version: '3'

services:
#  bot:
#    image: 421p/mophpidy
#    environment:
#      - MOPIDY_URI
#      - TELEGRAM_TOKEN
#      - BOT_USERNAME
#      - ADMIN
#    depends_on:
#      - redis
  redis:
    image: redis
    command: 'redis-server --appendonly yes'
